### ISSUE TITLE
Multiple errors

### ISSUE THREAD

**Issue by szymor** [Ostrea/SDL-2D-Game#1]
The game is problematic to be built on recent Linux platforms - it lacks some header declarations (functional and stdexcept). After compilation, it has runtime issues with fonts and images, which are not part of the repository. Please update it.

**Comment by Ostrea** [comment]
Sorry, but I don't think I have the files anymore and I also haven't touched C++ for ages. But as far as I remember these headers are part of a standard library. Maybe you aren't using C++11 (I think they part of it)? As for images and fonts - I think fonts are publicly available or you can use whatever fonts you want. And images are sadly lost to history :( But you can use any freely available or your own images.
